### ISSUE TITLE
Custom component does not compile with ESPHome 2022.1.2

### ISSUE THREAD

**Issue by dennisvbussel** [x3e/Itho-RFT-CO2-ESPHome#1]
The custom component does not compile (ESPHome version 2022.1.2).

It appears that there is an incompatibility with the SoftwareSerial library and std datatypes. I'm not sure how to fix these and perhaps you know a simple solution.

Yaml and ESPHome log below:

```
substitutions:
  device_name: mk-wtw-co2-itho
  friendly_name: Meterkast WTW CO2 Itho

esphome:
  name: '${device_name}'
  platform: ESP8266
  board: nodemcuv2
  includes:
    - Itho-RFT-CO2-ESPHome/ithofanComponent/
  libraries: 
    - SPI
    - SoftwareSerial

custom_component:
- id: fan
  lambda: |-
    auto fan = new IthoFan(5, 0x1C, 0x957D19, 0x9568C4);
    return {fan};
    
switch:
  - platform: template
    name: "${friendly_name} auto"
    id: switch_auto
    icon: mdi:molecule-co2
    turn_on_action:
      - lambda: fanPtr->setStatus(FanStatus::automatic);
  - platform: template
    name: "${friendly_name} night"
    id: switch_night
    icon: mdi:weather-night
    turn_on_action:
      - lambda: fanPtr->setStatus(FanStatus::night);
  - platform: template
    name: "${friendly_name} low"
    id: switch_low
    icon: mdi:fan-speed-1
    turn_on_action:
      - lambda: fanPtr->setStatus(FanStatus::low);
  - platform: template
    name: "${friendly_name} medium"
    id: switch_medium
    icon: mdi:fan-speed-2
    turn_on_action:
      - lambda: fanPtr->setStatus(FanStatus::medium);
  - platform: template
    name: "${friendly_name} high"
    id: switch_high
    icon: mdi:fan-speed-3
    turn_on_action:
      - lambda: fanPtr->setStatus(FanStatus::high);
      
number:
  - platform: template
    name: "${friendly_name} timer"
    id: timer_number
    icon: mdi:av-timer
    min_value: 0
    max_value: 255
    step: 1
    set_action:
      - lambda: fanPtr->setTimer(x);
  
sensor:
  - platform: template
    name: "${friendly_name} humidity"
    id: humidity_sensor
    icon: mdi:water-percent
    unit_of_measurement: '%'
    accuracy_decimals: 0
  - platform: template
    name: "${friendly_name} speed"
    id: rpm_sensor
    icon: mdi:rotate-right
    unit_of_measurement: 'rpm'
    accuracy_decimals: 0
    
# Enable logging
logger:

# Enable Home Assistant API
api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: esphome_itho.local
  
  ap:
    ssid: "Mk-Wtw-Co2-Itho Fallback Hotspot"
    password: !secret default_password

captive_portal:
```

```
INFO Reading configuration /config/esphome/mk-wtw-co2-itho.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing mk-wtw-co2-itho (board: nodemcuv2; framework: arduino; platform: platformio/espressif8266 @ 2.6.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|-- <SPI> 1.0
|-- <SoftwareSerial> 1.0.0
|-- <ESPAsyncWebServer-esphome> 2.1.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
Compiling /data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/src/IthoController.cpp.o
In file included from src/IthoController.cpp:1:0:
src/IthoController.h:16:34: error: 'std::function' has not been declared
     void addChangedCallback(std::function<void(void)> callback);
                                  ^
src/IthoController.h:16:42: error: expected ',' or '...' before '<' token
     void addChangedCallback(std::function<void(void)> callback);
                                          ^
src/IthoController.h:36:17: error: 'function' is not a member of 'std'
     std::vector<std::function<void(void)>> callbacks;
                 ^
src/IthoController.h:36:17: error: 'function' is not a member of 'std'
src/IthoController.h:36:41: error: template argument 1 is invalid
     std::vector<std::function<void(void)>> callbacks;
                                         ^
src/IthoController.h:36:41: error: template argument 2 is invalid
Compiling /data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/src/main.cpp.o
Generating LD script /data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/ld/local.eagle.app.v6.common.ld
Compiling /data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/lib975/ESPAsyncTCP-esphome/AsyncPrinter.cpp.o
Compiling /data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/lib975/ESPAsyncTCP-esphome/ESPAsyncTCP.cpp.o
Compiling /data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/lib975/ESPAsyncTCP-esphome/ESPAsyncTCPbuffer.cpp.o
Compiling /data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/lib975/ESPAsyncTCP-esphome/SyncClient.cpp.o
src/IthoController.cpp: In constructor 'IthoController::IthoController(int8_t, uint8_t, uint32_t, uint32_t)':
src/IthoController.cpp:23:32: error: no matching function for call to 'SoftwareSerial::SoftwareSerial()'
     remoteAddress(remoteAddress) {}
                                ^
src/IthoController.cpp:23:32: note: candidates are:
In file included from src/IthoController.h:4:0,
                 from src/IthoController.cpp:1:
/data/mk-wtw-co2-itho/.piolibdeps/mk-wtw-co2-itho/SoftwareSerial/SoftwareSerial.h:119:3: note: SoftwareSerial::SoftwareSerial(uint8_t, uint8_t, bool)
   SoftwareSerial(uint8_t receivePin, uint8_t transmitPin, bool inverse_logic = false);
   ^
/data/mk-wtw-co2-itho/.piolibdeps/mk-wtw-co2-itho/SoftwareSerial/SoftwareSerial.h:119:3: note:   candidate expects 3 arguments, 0 provided
/data/mk-wtw-co2-itho/.piolibdeps/mk-wtw-co2-itho/SoftwareSerial/SoftwareSerial.h:82:7: note: constexpr SoftwareSerial::SoftwareSerial(const SoftwareSerial&)
 class SoftwareSerial : public Stream
       ^
/data/mk-wtw-co2-itho/.piolibdeps/mk-wtw-co2-itho/SoftwareSerial/SoftwareSerial.h:82:7: note:   candidate expects 1 argument, 0 provided
src/IthoController.cpp: In member function 'bool IthoController::init()':
src/IthoController.cpp:68:30: error: 'SWSERIAL_8N1' was not declared in this scope
     radioSerial.begin(38400, SWSERIAL_8N1, radioIo0Pin, radioIo0Pin, false, 128);
                              ^
src/IthoController.cpp: At global scope:
src/IthoController.cpp:72:6: error: prototype for 'void IthoController::addChangedCallback(std::function<void()>)' does not match any in class 'IthoController'
 void IthoController::addChangedCallback(std::function<void(void)> callback) {
      ^
In file included from src/IthoController.cpp:1:0:
src/IthoController.h:16:10: error: candidate is: void IthoController::addChangedCallback(int)
     void addChangedCallback(std::function<void(void)> callback);
          ^
src/IthoController.cpp: In member function 'void IthoController::receivingMode(bool)':
src/IthoController.cpp:127:15: error: 'class SoftwareSerial' has no member named 'enableTx'
   radioSerial.enableTx(!receiving);
               ^
src/IthoController.cpp: In member function 'void IthoController::changed()':
src/IthoController.cpp:182:26: error: no matching function for call to 'begin(int&)'
     for (auto callback : callbacks) {
                          ^
src/IthoController.cpp:182:26: note: candidates are:
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/vector:66:0,
                 from src/cc1101.h:4,
                 from src/IthoController.h:3,
                 from src/IthoController.cpp:1:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:87:5: note: template<class _Tp, unsigned int _Nm> _Tp* std::begin(_Tp (&)[_Nm])
     begin(_Tp (&__arr)[_Nm])
     ^
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:87:5: note:   template argument deduction/substitution failed:
src/IthoController.cpp:182:26: note:   mismatched types '_Tp [_Nm]' and 'int'
     for (auto callback : callbacks) {
                          ^
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/vector:66:0,
                 from src/cc1101.h:4,
                 from src/IthoController.h:3,
                 from src/IthoController.cpp:1:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:58:5: note: template<class _Container> decltype (__cont.begin()) std::begin(const _Container&)
     begin(const _Container& __cont) -> decltype(__cont.begin())
     ^
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:58:5: note:   template argument deduction/substitution failed:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h: In substitution of 'template<class _Container> decltype (__cont.begin()) std::begin(const _Container&) [with _Container = int]':
src/IthoController.cpp:182:26:   required from here
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:58:5: error: request for member 'begin' in '__cont', which is of non-class type 'const int'
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:48:5: note: template<class _Container> decltype (__cont.begin()) std::begin(_Container&)
     begin(_Container& __cont) -> decltype(__cont.begin())
     ^
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:48:5: note:   template argument deduction/substitution failed:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h: In substitution of 'template<class _Container> decltype (__cont.begin()) std::begin(_Container&) [with _Container = int]':
src/IthoController.cpp:182:26:   required from here
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:48:5: error: request for member 'begin' in '__cont', which is of non-class type 'int'
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/stl_vector.h:63:0,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/vector:64,
                 from src/cc1101.h:4,
                 from src/IthoController.h:3,
                 from src/IthoController.cpp:1:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/initializer_list:89:5: note: template<class _Tp> constexpr const _Tp* std::begin(std::initializer_list<_Tp>)
     begin(initializer_list<_Tp> __ils) noexcept
     ^
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/initializer_list:89:5: note:   template argument deduction/substitution failed:
src/IthoController.cpp:182:26: note:   mismatched types 'std::initializer_list<_Tp>' and 'int'
     for (auto callback : callbacks) {
                          ^
src/IthoController.cpp:182:26: error: no matching function for call to 'end(int&)'
src/IthoController.cpp:182:26: note: candidates are:
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/vector:66:0,
                 from src/cc1101.h:4,
                 from src/IthoController.h:3,
                 from src/IthoController.cpp:1:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:97:5: note: template<class _Tp, unsigned int _Nm> _Tp* std::end(_Tp (&)[_Nm])
     end(_Tp (&__arr)[_Nm])
     ^
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:97:5: note:   template argument deduction/substitution failed:
src/IthoController.cpp:182:26: note:   mismatched types '_Tp [_Nm]' and 'int'
     for (auto callback : callbacks) {
                          ^
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/vector:66:0,
                 from src/cc1101.h:4,
                 from src/IthoController.h:3,
                 from src/IthoController.cpp:1:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:78:5: note: template<class _Container> decltype (__cont.end()) std::end(const _Container&)
     end(const _Container& __cont) -> decltype(__cont.end())
     ^
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:78:5: note:   template argument deduction/substitution failed:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h: In substitution of 'template<class _Container> decltype (__cont.end()) std::end(const _Container&) [with _Container = int]':
src/IthoController.cpp:182:26:   required from here
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:78:5: error: request for member 'end' in '__cont', which is of non-class type 'const int'
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:68:5: note: template<class _Container> decltype (__cont.end()) std::end(_Container&)
     end(_Container& __cont) -> decltype(__cont.end())
     ^
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:68:5: note:   template argument deduction/substitution failed:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h: In substitution of 'template<class _Container> decltype (__cont.end()) std::end(_Container&) [with _Container = int]':
src/IthoController.cpp:182:26:   required from here
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/range_access.h:68:5: error: request for member 'end' in '__cont', which is of non-class type 'int'
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/bits/stl_vector.h:63:0,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/vector:64,
                 from src/cc1101.h:4,
                 from src/IthoController.h:3,
                 from src/IthoController.cpp:1:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/initializer_list:99:5: note: template<class _Tp> constexpr const _Tp* std::end(std::initializer_list<_Tp>)
     end(initializer_list<_Tp> __ils) noexcept
     ^
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/4.8.2/initializer_list:99:5: note:   template argument deduction/substitution failed:
src/IthoController.cpp:182:26: note:   mismatched types 'std::initializer_list<_Tp>' and 'int'
     for (auto callback : callbacks) {
                          ^
Compiling /data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/lib975/ESPAsyncTCP-esphome/tcp_axtls.c.o
Compiling /data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/libf5a/SPI/SPI.cpp.o
Compiling /data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/lib671/SoftwareSerial/SoftwareSerial.cpp.o
/data/mk-wtw-co2-itho/.piolibdeps/mk-wtw-co2-itho/SoftwareSerial/SoftwareSerial.cpp:41:27: fatal error: avr/interrupt.h: No such file or directory
 #include <avr/interrupt.h>
                           ^
compilation terminated.
*** [/data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/lib671/SoftwareSerial/SoftwareSerial.cpp.o] Error 1
Compiling /data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/libaf0/Hash/Hash.cpp.o
*** [/data/mk-wtw-co2-itho/.pioenvs/mk-wtw-co2-itho/src/IthoController.cpp.o] Error 1
========================== [FAILED] Took 2.16 seconds ==========================
```
